import type { RootInfo, SElement, SFragment } from '../shared/protocol.ts';
import { normalizeTree, type NormalizeOptions } from '../dom/normalize.ts';
import { getAttr, isElement, textContent, walk } from '../dom/tree.ts';
import type { Draft } from './draft.ts';

// Whole-document checks: duplicate ids (and useId collisions between React
// roots), and <head> content that changed while the page hydrated.

/** Ids generated by React's useId (18: `:R1:`, 19.0/19.1: `«R1»`, 19.2+: `_R_1_`). */
export const USE_ID_PATTERN: RegExp = /(?::[rR][0-9a-zA-Z]*:|«[rR][0-9a-zA-Z]*»|_[rR]_[0-9a-zA-Z]*_)/;

const MAX_DUPLICATES = 20;

function elementsById(tree: SFragment): Map<string, SElement[]> {
  const byId = new Map<string, SElement[]>();
  const visit = (nodes: readonly SFragment['children'][number][], inTemplate: boolean): void => {
    for (const node of nodes) {
      if (!isElement(node)) continue;
      if (node.ignored) continue;
      const id = getAttr(node, 'id');
      if (id && !inTemplate) {
        const list = byId.get(id) ?? [];
        list.push(node);
        byId.set(id, list);
      }
      visit(node.children, inTemplate);
      if (node.shadow) visit(node.shadow, true);
      if (node.content) visit(node.content, true);
    }
  };
  visit(tree.children, false);
  return byId;
}

export function analyzeDuplicateIds(tree: SFragment, roots: readonly RootInfo[], normalize: NormalizeOptions): Draft[] {
  const normalized = normalizeTree(tree, normalize).tree;
  const appRoots = roots.filter((root) => !root.tooling && root.mode === 'hydrate');
  const unprefixed = appRoots.filter((root) => root.identifierPrefix === undefined);
  const drafts: Draft[] = [];
  for (const [id, elements] of elementsById(normalized)) {
    if (elements.length < 2) continue;
    if (drafts.length >= MAX_DUPLICATES) break;
    const tags = [...new Set(elements.map((element) => `<${element.tag}>`))].join(', ');
    const fromUseId = USE_ID_PATTERN.test(id) && unprefixed.length >= 2;
    const draft: Draft = fromUseId
      ? {
          code: 'HP3004',
          stage: 'stable',
          confidence: 0.85,
          selector: `#${cssEscape(id)}`,
          key: id,
          message: `${elements.length} elements (${tags}) have the React-generated id "${id}". ${unprefixed.length} React roots on this page use useId without an identifierPrefix, so each one generates the same ids.`,
          evidence: [{ kind: 'note', message: `Roots without identifierPrefix: ${unprefixed.map((root) => root.containerSelector).join(', ')}.` }],
          nodeId: elements[0]!.id,
        }
      : {
          code: 'HP3003',
          stage: 'stable',
          confidence: 0.9,
          selector: `#${cssEscape(id)}`,
          key: id,
          message: `${elements.length} elements (${tags}) have id="${id}". Labels, ARIA references and getElementById find only the first one.`,
          evidence: [],
          nodeId: elements[0]!.id,
        };
    drafts.push(draft);
  }
  return drafts;
}

function cssEscape(id: string): string {
  return /^[A-Za-z_][\w-]*$/.test(id) ? id : id.replace(/[^\w-]/g, (char) => `\\${char.codePointAt(0)!.toString(16)} `);
}

interface HeadValues {
  titles: string[];
  /** `name=description` → contents, in document order. */
  meta: Map<string, { selector: string; contents: string[] }>;
  stylesheets: Set<string>;
}

function headOf(tree: SFragment): HeadValues {
  const values: HeadValues = { titles: [], meta: new Map(), stylesheets: new Set() };
  let head: SElement | undefined;
  walk(tree, (node) => {
    if (!head && isElement(node) && node.tag === 'head') head = node;
  });
  if (!head) return values;
  for (const child of head.children) {
    if (!isElement(child)) continue;
    if (child.tag === 'title') values.titles.push(textContent(child).trim());
    if (child.tag === 'meta') {
      for (const attribute of ['name', 'property', 'http-equiv', 'itemprop'] as const) {
        const key = getAttr(child, attribute);
        const content = getAttr(child, 'content');
        if (!key || content === null) continue;
        const entry = values.meta.get(`${attribute}=${key}`) ?? { selector: `head > meta[${attribute}="${key}"]`, contents: [] };
        entry.contents.push(content);
        values.meta.set(`${attribute}=${key}`, entry);
      }
    }
    if (child.tag === 'link' && /(^|\s)stylesheet(\s|$)/i.test(getAttr(child, 'rel') ?? '')) {
      const href = getAttr(child, 'href');
      if (href) values.stylesheets.add(href);
    }
  }
  return values;
}

const list = (values: readonly string[]): string => values.map((value) => JSON.stringify(value)).join(', ');

/**
 * <head> values that differ between the pre-hydration DOM and the page after
 * hydration effects. React 19 adds a new <title>/<meta> next to the server's
 * instead of changing it, so values are compared as sets.
 */
export function analyzeHead(before: SFragment, after: SFragment, normalize: NormalizeOptions): Draft[] {
  const pre = headOf(normalizeTree(before, normalize).tree);
  const post = headOf(normalizeTree(after, normalize).tree);
  const drafts: Draft[] = [];
  const base = { code: 'HP1014' as const, stage: 'post-effect' as const, confidence: 0.75, evidence: [] };
  const newTitles = post.titles.filter((title) => !pre.titles.includes(title));
  if (pre.titles.length > 0 && newTitles.length > 0) {
    const several = post.titles.length > 1;
    drafts.push({
      ...base,
      selector: 'head > title',
      attribute: 'title',
      server: pre.titles.join(' | '),
      client: newTitles.join(' | '),
      message: `The server rendered the title ${list(pre.titles)}; hydration added ${list(newTitles)}.${several ? ` The page now has ${post.titles.length} <title> elements and the browser shows the first one.` : ''} Search engines and link previews see the server title.`,
    });
  }
  for (const [key, entry] of pre.meta) {
    const added = (post.meta.get(key)?.contents ?? []).filter((content) => !entry.contents.includes(content));
    if (added.length === 0) continue;
    drafts.push({
      ...base,
      selector: entry.selector,
      attribute: 'content',
      server: entry.contents.join(' | '),
      client: added.join(' | '),
      message: `<meta ${key.replace('=', '="')}"> was ${list(entry.contents)} in the server HTML; hydration added ${list(added)}.`,
    });
  }
  for (const href of pre.stylesheets) {
    if (post.stylesheets.has(href)) continue;
    drafts.push({
      ...base,
      selector: `head > link[href="${href}"]`,
      server: href,
      client: null,
      message: `The stylesheet ${href} from the server HTML was removed while the page hydrated, which can make the page flash without styles.`,
    });
  }
  return drafts;
}
