// Generates docs/issues.md and the config JSON Schema from their single sources of truth.
// Usage: node scripts/generate-docs.ts [--check]

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { ISSUES, docsUrl } from '../packages/hydration-proof/src/issues/registry.ts';
import { suggestionsFor } from '../packages/hydration-proof/src/issues/suggestions.ts';
import { configJsonSchema } from '../packages/hydration-proof/src/config/schema.ts';
import { reportJsonSchema } from '../packages/hydration-proof/src/report/schema.ts';
import { CAUSES, causeDocsUrl } from '../packages/hydration-proof/src/diagnose/index.ts';

const check = process.argv.includes('--check');
const GROUPS: [string, string][] = [
  ['HP1', 'DOM mismatches'],
  ['HP2', 'Problems React reported'],
  ['HP3', 'Markup the browser repaired'],
  ['HP4', 'Changes made outside React'],
  ['HP5', 'Interaction during hydration'],
  ['HP6', 'suppressHydrationWarning audit'],
  ['HP9', 'Test run problems'],
];

let markdown = `# Issue codes

<!-- Generated by scripts/generate-docs.ts from src/issues/registry.ts. Do not edit. -->

Every finding has a stable code. Codes never change meaning, so you can use
them in ignore rules and baselines.

| Code | Severity | Title |
| --- | --- | --- |
${[...ISSUES.values()].map((issue) => `| [${issue.code}](#${issue.code.toLowerCase()}) | ${issue.severity} | ${issue.title} |`).join('\n')}
`;

for (const [prefix, heading] of GROUPS) {
  const issues = [...ISSUES.values()].filter((issue) => issue.code.startsWith(prefix));
  if (issues.length === 0) continue;
  markdown += `\n## ${heading}\n`;
  for (const issue of issues) {
    markdown += `\n### ${issue.code}\n\n**${issue.title}** · \`${issue.name}\` · default severity: ${issue.severity}\n\n${issue.description}\n`;
    const suggestions = suggestionsFor(issue.code);
    if (suggestions.length > 0) markdown += `\nHow to fix:\n\n${suggestions.map((line) => `- ${line}`).join('\n')}\n`;
    markdown += `\nOnline: ${docsUrl(issue.code)}\n`;
  }
}

let causes = `# Likely causes

<!-- Generated by scripts/generate-docs.ts from src/diagnose/index.ts. Do not edit. -->

Every finding gets the most likely cause, with a confidence score. The
diagnosis combines the shape of the two values (timestamps, number formats,
random tokens, generated class names), the source code around the element
(\`Date.now()\`, \`localStorage\`, \`matchMedia\`, ...), the scenario (locale,
timezone, color scheme, viewport) and the stage where the difference started.

| Cause | Title |
| --- | --- |
${Object.entries(CAUSES).map(([id, cause]) => `| [\`${id}\`](#${id}) | ${cause.title} |`).join('\n')}
`;
for (const [id, cause] of Object.entries(CAUSES)) {
  causes += `\n## ${id}\n\n**${cause.title}**\n\n${cause.fixes.map((fix) => `- ${fix}`).join('\n')}\n\nOnline: ${causeDocsUrl(id)}\n`;
}

const outputs: [string, string][] = [
  ['docs/issues.md', markdown],
  ['docs/causes.md', causes],
  ['packages/hydration-proof/schema/config.json', `${JSON.stringify(configJsonSchema(), null, 2)}\n`],
  ['packages/hydration-proof/schema/report.json', `${JSON.stringify(reportJsonSchema(), null, 2)}\n`],
];

let stale = false;
for (const [file, content] of outputs) {
  let current = '';
  try {
    current = readFileSync(file, 'utf8');
  } catch {
    current = '';
  }
  if (current === content) continue;
  if (check) {
    console.error(`${file} is out of date. Run: node scripts/generate-docs.ts`);
    stale = true;
  } else {
    mkdirSync(file.slice(0, file.lastIndexOf('/')), { recursive: true });
    writeFileSync(file, content);
    console.log(`wrote ${file}`);
  }
}
if (stale) process.exitCode = 1;
